### ISSUE TITLE
library(torch) wrong

### ISSUE THREAD

**Issue by db-beep** [mlverse/torch#1066]
library(torch)
Warning message:
ℹ torch failed to start, restart your R session to try again.
ℹ You might need to reinstall torch using `install_torch()`
✖ /home/server/R/x86_64-pc-linux-gnu-library/4.1/torch/lib/liblantern.so
  - libcudart.so.11.0: Unable to open shared object file: there is no file or directory available
Caused by error in `cpp_lantern_init()`:
! /home/server/R/x86_64-pc-linux-gnu-library/4.1/torch/lib/liblantern.so - libcudart.so.11.0: Unable to open shared object file: there is no file or directory available

I have installed cuda11.6 with torch version 0.10.0.
Ubuntu22.04 
Rstudio-server1.7.1 
R-base-4.1.3

**Comment by dfalbel** [comment]
This probably means that CUDA could not be found. Can you verify the location of libcudart in your system?
You can also try installing the pre-buiult binaries following: https://torch.mlverse.org/docs/articles/installation.html#installing-from-pre-built-binaries as those include the necessary cuda dependencies only requiring the GPU driver to be installed.

**Comment by db-beep** [comment]
Hello, the libcudart file in Ubuntu 22.04 system is located in/usr/local/cud-11.6/.

**Comment by dfalbel** [comment]
You might need to add that location to `LD_LIBRARY_PATH`

**Comment by db-beep** [comment]
see you 
![image](https://github.com/mlverse/torch/assets/84955116/a604c2bd-16ed-4bbe-ad62-5325c8d1b592)
![image](https://github.com/mlverse/torch/assets/84955116/74158a17-505a-4a55-a42b-d79150bcc864)

**Comment by db-beep** [comment]
Pre build binaries are calculated directly using the CPU without utilizing the GPU. But if you don't use pre build binaries to install torch, the result is still an error and libcudart.so.11. o cannot be found.pre built binaries

**Comment by db-beep** [comment]
Problem with linking libnvToolsExt and libcudart on Ubuntu #298

**Comment by db-beep** [comment]
I have found a solution, but there is a lack of soft connections. Symbol link

**Comment by db-beep** [comment]
> library(torch)
> t1 <- torch_tensor(1)
> t1
torch_tensor
 1
[ CPUFloatType{1} ]
> t1$device
torch_device(type='cpu')
> t2 <- t1$to(device = "cuda")
> t2
torch_tensor
 1
[ CUDAFloatType{1} ]

**Comment by db-beep** [comment]
thanks,
