### ISSUE TITLE
CUDA not detected on Windows 10 2004

### ISSUE THREAD

**Issue by aminadibi** [mlverse/torch#301]
I have Visual Studio and CUDA 10.2 installed on Windows 10, and I have manually set `CUDA_HOME` as well, yet no luck:

```> library(torch)
> torch_tensor(1, device = "cuda")
Error in cpp_torch_tensor(data, rev(dimension), options$ptr, requires_grad,  : 
  PyTorch is not linked with support for cuda devices (getDeviceGuardImpl at C:\b\windows\pytorch\c10/core/impl/DeviceGuardImplInterface.h:216)
(no backtrace available)
> Sys.getenv("CUDA_HOME")
[1] "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2"
```

Here is my session info:

```
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_Canada.1252  LC_CTYPE=English_Canada.1252   
[3] LC_MONETARY=English_Canada.1252 LC_NUMERIC=C                   
[5] LC_TIME=English_Canada.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] torch_0.1.0

loaded via a namespace (and not attached):
 [1] bit_4.0.4      compiler_4.0.2 R6_2.4.1       magrittr_1.5   tools_4.0.2   
 [6] Rcpp_1.0.5     tinytex_0.26   bit64_4.0.5    xfun_0.18      rlang_0.4.8
```

**Comment by dfalbel** [comment]
@aminadibi What happened is that `torch` didn't automatically install the `libtorch` with CUDA support because it was not detected when installing. 

Can you try setting the env var and reinstalling? Eg: 
```
Sys.setenv("CUDA_HOME"  = "...")
install.packages("torch")
library(torch) # here libtorch will be downloaded and installed.
```

**Comment by aminadibi** [comment]
Thanks. So I did that, but it seems to keep downloading the `cpu` version of `libtorch`:

```
> Sys.setenv("CUDA_HOME"  = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2")
> 
> install.packages("torch")
Error in install.packages : Updating loaded packages

Restarting R session...

> install.packages("torch")
Installing package into ‘C:/Users/amin/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.0/torch_0.1.0.zip'
Content type 'application/zip' length 12166719 bytes (11.6 MB)
downloaded 11.6 MB

package ‘torch’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\amin\AppData\Local\Temp\RtmpmQUu85\downloaded_packages
> library(torch)
trying URL 'https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.5.0.zip'
Content type 'application/zip' length 99725651 bytes (95.1 MB)
downloaded 95.1 MB

trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.1.0/latest/Windows-cpu.zip'
Content type 'application/zip' length 1436082 bytes (1.4 MB)
downloaded 1.4 MB

> torch_tensor(1, device = "cuda")
Error in cpp_torch_tensor(data, rev(dimension), options$ptr, requires_grad,  : 
  PyTorch is not linked with support for cuda devices (getDeviceGuardImpl at C:\b\windows\pytorch\c10/core/impl/DeviceGuardImplInterface.h:216)
(no backtrace available)
```

**Comment by aminadibi** [comment]
It seems that `install_type_windows` correctly identifies `CUDA`:

```
> install_type_windows("1.5.0")
[1] "10.2"
```
Also, it seems in Windows `CUDA_PATH` is used instead of `CUDA_HOME`, which makes sense:

```
> install_type_windows
function(version) {
  
  cuda_version <- NULL
  cuda_path <- Sys.getenv("CUDA_PATH")
  
  if (nchar(cuda_path) > 0) {
    versions_file <- file.path(cuda_path, "version.txt")
    if (file.exists(versions_file)) {
      cuda_version <- gsub("CUDA Version |\\.[0-9]+$", "", readLines(versions_file))
    }
  }
  
  if (is.null(cuda_version)) return("cpu")
  
  versions_available <- names(install_config[[version]])
  
  if (!cuda_version %in% versions_available) {
    message("Cuda ", cuda_version, " detected but torch only supports: ", paste(versions_available, collapse = ", "))
    return("cpu")
  }
  
  cuda_version
}
<bytecode: 0x00000178737566e8>
```
Still not sure why the CPU version installs.

**Comment by dfalbel** [comment]
Sorry! My bad! The problem is that GPU support on windows is recent and it's not yet available on CRAN:
You will need something like:

```
Sys.setenv("CUDA_HOME"  = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2")
remotes::install_github("mlverse/torch")
```

**Comment by aminadibi** [comment]
Ah that was it. Problem solved.

**Comment by faltinl** [comment]
The initial behavior here (apparently I have more or less the same environment as reported above) was exactly the one shown in the uppermost post. The command `Sys.setenv("CUDA_HOME"  = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2")` was accepted as well. However, what followed was quite different:

```
> Sys.setenv("CUDA_HOME"  = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2")
> remotes::install_github("mlverse/torch")
Downloading GitHub repo mlverse/torch@HEAD
√  checking for file 'C:\.....\Local\Temp\RtmpOy64DE\remotes9b0405625f1\mlverse-torch-ec29bb0/DESCRIPTION'
-  preparing 'torch': (3.5s)
√  checking DESCRIPTION meta-information 
-  cleaning src
-  checking for LF line-endings in source and make files and shell scripts (2.2s)
-  checking for empty or unneeded directories
   Removed empty directory 'torch/bench'
   Removed empty directory 'torch/docker'
   Removed empty directory 'torch/vignettes/examples'
-  building 'torch_0.1.0.9000.tar.gz'
   
* installing *source* package 'torch'
** using staged installation
** libs
c:/Rtools/mingw_64/bin/g++  -std=gnu++11 -I"C:/R362/include" -DNDEBUG  -I"C:/R362/library/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
In file included from C:/R362/include/R.h:91:0,
                 from C:/R362/library/Rcpp/include/Rcpp/r/headers.h:71,
                 from C:/R362/library/Rcpp/include/RcppCommon.h:29,
                 from C:/R362/library/Rcpp/include/Rcpp.h:27,
                 from torch_types.h:11,
                 from RcppExports.cpp:4:
C:/R362/include/R_ext/RS.h:55:0: warning: "ERROR" redefined
 #define ERROR   ),error(R_problem_buf);}
 ^
In file included from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/windows.h:71:0,
                 from lantern/lantern.h:8,
                 from torch_types.h:9,
                 from RcppExports.cpp:4:
C:/Rtools/mingw_64/x86_64-w64-mingw32/include/wingdi.h:75:0: note: this is the location of the previous definition
 #define ERROR 0
 ^
```
After the last line an apparently endless sequence of similar but not identical messages follows. Any hints to what I could do now to get a working installation of `torch for R`?

**Comment by dfalbel** [comment]
These errors can be safely ignored, it's the compiler complaining about the redefinition of a macro. However compilation takes ~15 minutes. Did you see a different error?

**Comment by faltinl** [comment]
Yes, there are many others looking quite similarly, but aren't. After many screens they end in the following sequence:

```
...
C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/sstream:502:11: error: use of deleted function 'std::basic_stringbuf<char>::basic_stringbuf(const std::basic_stringbuf<char>&)'
C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/sstream:64:11: note: 'std::basic_stringbuf<char>::basic_stringbuf(const std::basic_stringbuf<char>&)' is implicitly deleted because the default definition would be ill-formed:
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/ios:43:0,
                 from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/ostream:38,
                 from C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/iterator:64,
                 from C:/R362/library/Rcpp/include/RcppCommon.h:49,
                 from C:/R362/library/Rcpp/include/Rcpp.h:27,
                 from torch_types.h:11,
                 from tensor.cpp:2:
C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/streambuf:802:7: error: 'std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]' is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from C:/R362/library/Rcpp/include/RcppCommon.h:53:0,
                 from C:/R362/library/Rcpp/include/Rcpp.h:27,
                 from torch_types.h:11,
                 from tensor.cpp:2:
C:/Rtools/mingw_64/x86_64-w64-mingw32/include/c++/sstream:64:11: error: within this context
     class basic_stringbuf : public basic_streambuf<_CharT, _Traits>
           ^
tensor.cpp:17:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (cont.size() > n && n > 1)
                   ^
tensor.cpp:24:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < cont.size(); i ++)
                     ^
tensor.cpp:28:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (i != (cont.size() - 1))
           ^
tensor.cpp:31:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if (i == (cont.size() - 2) && truncated)
           ^
make: *** [C:/R362/etc/x64/Makeconf:215: tensor.o] Error 1
ERROR: compilation failed for package 'torch'
* removing 'C:/R362/library/torch'
Error: Failed to install 'torch' from GitHub:
  (converted through warning) installation of package ‘C:/Users/lf/AppData/Local/Temp/RtmpALpXGT/file1f6441f1e4b/torch_0.1.0.9000.tar.gz’ had non-zero exit status
```

**Comment by dfalbel** [comment]
It could be a problem related to R 3.6 which we are not currently testing in the CI.
Would you consider updating to R 4.0.x? I will still try to debug if that's the cause.

**Comment by faltinl** [comment]
That would probably open up a vicious circle of other problems, not least of all with Tensorflow & Keras, I suppose. In the meantime, I have disvovered, that I don't have a file `C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.2` but only `...v10.1`. (The results shown in my last post were obtained using `...10.1` btw). Could that cause the problems?

**Comment by dfalbel** [comment]
The CRAN version is not yet updated with the Windows GPU support, and installing from CRAN is good because you get the binaries directly and do not need to build from source. 

I am working on support building torch from source with R3.6... Otherwise what you could do is to manually run this:

```
Sys.setenv("CUDA_HOME"  = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1")
source("https://raw.githubusercontent.com/mlverse/torch/master/R/install.R")
install_torch(reinstall = TRUE)
```

or wait for the next CRAN release in the next few days.

**Comment by faltinl** [comment]
That seemed to work:
 
```
> install_torch(reinstall = TRUE)
trying URL 'https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-1.5.0%2Bcu101.zip'
Content type 'application/zip' length 838392117 bytes (799.6 MB)
downloaded 799.6 MB
```

Then, however: 

```
trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/master/latest/Windows-gpu-101.zip'
Content type 'application/zip' length 1440308 bytes (1.4 MB)
downloaded 1.4 MB
Errorin lantern_start(reload = TRUE) : 
  could not find "lantern_start" 
```
Sorry to bother you again and again...

**Comment by dfalbel** [comment]
Ok, the download seems fine. What happens when you restart your session and `library(torch)`.

**Comment by faltinl** [comment]
Well - great surprise (for me - probably not for you!-):

```
> library(torch)
Warning:
Package ‘torch’ has been created under R version 3.6.3 
> torch_tensor(1, device = "cuda")
torch_tensor 
 1
[ CUDAFloatType{1} ]
> 
```
Yeah, that's it! Thank you so much, Daniel, for your support!

**Comment by jdmassman** [comment]
I just tried this and it didn't work. Still loads the cpu version instead of gpu.
```{r}
 > Sys.setenv("CUDA_HOME"  = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1")
 > Sys.setenv("CUDA_PATH"  = "C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.1")
 > devtools::install_github("mlverse/torch", force = T)
 > library(torch)
trying URL 'https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-1.5.0.zip'
Content type 'application/zip' length 99725651 bytes (95.1 MB)
downloaded 95.1 MB

trying URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/master/latest/Windows-cpu.zip'
Content type 'application/zip' length 1454689 bytes (1.4 MB)
downloaded 1.4 MB

> cuda_is_available()
[1] FALSE
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

other attached packages:
[1] torch_0.1.1.9000

**Comment by dfalbel** [comment]
Hi @jdmassman ! We do currently support CUDA 11.0. Can you try installing 10.1 or 10.2 and trying again?

**Comment by jdmassman** [comment]
That fixed it! Thanks much!

> library(torch)
trying URL '
https://download.pytorch.org/libtorch/cu102/libtorch-win-shared-with-deps-1.5.0.zip
'
Content type 'application/zip' length 877871836 bytes (837.2 MB)
downloaded 837.2 MB

trying URL '
https://storage.googleapis.com/torch-lantern-builds/refs/heads/master/latest/Windows-gpu-102.zip
'
Content type 'application/zip' length 1454424 bytes (1.4 MB)
downloaded 1.4 MB

> cuda_is_available()
[1] TRUE
> torch_tensor(1, device = "cuda:0")
torch_tensor
 1
[ CUDAFloatType{1} ]

**Comment by Unco3892** [comment]
Hi, the GPU installation issue seems to persist with CUDA 10.1 despite having the right environment variables.  `CUDA` and `cuDNN` are correctly configured as I'm currently using `tensorflow` on GPU without any problems.

```
> Sys.getenv(c("CUDA_HOME", "CUDA_PATH"))
                                                     CUDA_HOME 
"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1" 
                                                     CUDA_PATH 
"C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v10.1"
> library(torch)
> cuda_is_available()
[1] FALSE
> torch_tensor(1, device = "cuda")
Error in cpp_torch_tensor(data, rev(dimension), options, requires_grad,  : 
  PyTorch is not linked with support for cuda devices
Exception raised from getDeviceGuardImpl at ..\..\c10/core/impl/DeviceGuardImplInterface.h:224 (most recent call first):
00007FF8CE5C0EC200007FF8CE5C0E60 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF8CE5C0B3E00007FF8CE5C0AF0 c10.dll!c10::detail::torchCheckFail [<unknown file> @ <unknown line number>]
00007FF88E462B7400007FF88E462790 torch_cpu.dll!torch::jit::Method::get_executor [<unknown file> @ <unknown line number>]
00007FF88E753F2800007FF88E753D00 torch_cpu.dll!at::native::to [<unknown file> @ <unknown line number>]
00007FF88ED58B1100007FF88EB3A9F0 torch_cpu.dll!at::zeros_outf [<unknown file> @ <unknown line number>]
00007FF88ED352D000007FF88EB3A9F0 torch_cpu.dll!at::zeros_outf [<unknown file> @ <unknown line number>]
00007FF88ED2548E00007FF88EB3A9F0 torch_cpu.dll!at::zeros_outf [<unknown file> @ <unknown line number>]
00007FF88EDA128E00007FF88ED93D70 torch_cpu.dll!at::is_custom_op [<unkno
```

**Comment by dfalbel** [comment]
Can you try `torch::install_torch(reinstall = TRUE)` and see what libtorch URL is being queried? Maybe our code that detects if a GPU is available is not able to detect your installation and thus is installing the CPU version of libtorch.

**Comment by Unco3892** [comment]
Thanks for your quick reply. Interestingly `torch::install_torch(reinstall = TRUE)` doesn't actually output anything:
```
> torch::install_torch(reinstall = TRUE) 
> 
```
Nevertheless, I also sourced the script and here's the output:
```
> source("https://raw.githubusercontent.com/mlverse/torch/master/R/install.R")
> install_torch(reinstall = TRUE)
essai de l'URL 'https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-1.8.0%2Bcu101.zip'
Content type 'application/zip' length 1269172281 bytes (1210.4 MB)
downloaded 1210.4 MB

essai de l'URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/master/latest/Windows-gpu-101.zip'
Content type 'application/zip' length 1533985 bytes (1.5 MB)
downloaded 1.5 MB

Error in lantern_start(reload = TRUE) : 
  impossible de trouver la fonction "lantern_start"
```
So instead, I removed the `torch` and install it again from CRAN (same problem with dev version):
```
> library(torch)
essai de l'URL 'https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-1.8.0%2Bcu101.zip'
Content type 'application/zip' length 1269172281 bytes (1210.4 MB)
downloaded 1210.4 MB

essai de l'URL 'https://storage.googleapis.com/torch-lantern-builds/refs/heads/cran/v0.3.0/latest/Windows-gpu-101.zip'
Content type 'application/zip' length 1549493 bytes (1.5 MB)
downloaded 1.5 MB

Warning message:
le package ‘torch’ a été compilé avec la version R 4.0.5 
```
The url seems to be GPU version so I guess the issue may be elsewhere.

p.s. apologize for the French output.

**Comment by faltinl** [comment]
Hi, Daniel!
Bearing in mind your friendly admonition of October 15, 2020, to install `R4.0.x`, I have updated to version `R4.0.5` in the meantime - and since then I keep getting _exactly the same feedback_ as reported by [Unco3892](https://github.com/Unco3892) in his last message above. And that after `Torch` lastly worked fine under R3.6.2 (see my message from October 16, 2020) ... 🙄

**Comment by dfalbel** [comment]
HI sorry for that. I don't have a good idea for why exactly it's not working. Looking at pytorch issues this issue seems to be related to linking:

See for https://github.com/pytorch/pytorch/issues/48291 and https://github.com/pytorch/pytorch/issues/54131

AFAICT we are doing everything that was proposed there, so I'll take some time to debug this early next week.

**Comment by dfalbel** [comment]
FWIW I created a new issue #577 so its easier to track without having to go back to a closed one.
