### ISSUE TITLE
dataloader CUDA memory issues

### ISSUE THREAD

**Issue by LordRudolf** [mlverse/torch#447]
I am following this R torch example https://mlverse.github.io/torchbook/image-classification.html .
I am facing with the CUDA memory issues. The error message is as follows:

```
Error in (function (input, weight, bias, running_mean, running_var, training,  : 
  CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 8.00 GiB total capacity; 4.92 GiB already allocated; 97.57 MiB free; 5.12 GiB reserved in total by PyTorch)
Exception raised from malloc at ..\..\c10\cuda\CUDACachingAllocator.cpp:272 (most recent call first):
00007FF9D269A7B200007FF9D269A750 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FF9DEE3A84600007FF9DEE3A7D0 c10_cuda.dll!c10::CUDAOutOfMemoryError::CUDAOutOfMemoryError [<unknown file> @ <unknown line number>]
00007FF9DEE412A700007FF9DEE3FF80 c10_cuda.dll!c10::cuda::CUDACachingAllocator::init [<unknown file> @ <unknown line number>]
00007FF9DEE4144A00007FF9DEE3FF80 c10_cuda.dll!c10::cuda::CUDACachingAllocator::init [<unknown file> @ <unknown line number>]
00007FF9DEE35BEA00007FF9DEE359F0 c10_cuda.dll!c10::cuda::set_device [<unknown file> @ <unknown line number>]
00007FF97B6281B100007FF97B628070 torch_cuda.dll!at::native::empty_cuda [<unknown file> @ <unknown line number>]
00007FF97B79245E0 
```

I tried the popular suggestion to reduce the batch size (reduced from 64 to 16). It gave zero improvements. However, according to the StakOverflow posts concerning the python version of Torch, the issue is related to the dataloader function which has nothing to do with the batch size.  I have NVIDIA GeForce RTX 2080 8 GB and 12 x 3.20 GHz CPU processors, therefore, it is no wonder why GPU memory becomes overloaded. One solution would be to explicitly show the number of subprocesses to use for data loading. using the function's dataloader argument "num_workers". But then I've got a new error:

```
Error: callr subprocess failed: could not find function "transform_normalize"
Run `rlang::last_error()` to see where the error occurred.
```
```
>rlang::last_error()
<error/runtime_error>
callr subprocess failed: could not find function "transform_normalize"
Backtrace:
  1. global::train_batch(b)
  9. torch:::`[[.enum_env`(b, 1)
 10. parent.env(x)$.iter$.next()
 11. self$.next_data()
 12. self$.pop_task()
 13. torch:::runtime_error(result$error$message)
Run `rlang::last_trace()` to see the full context.

>rlang::last_trace()
<error/runtime_error>
callr subprocess failed: could not find function "transform_normalize"
Backtrace:
     x
  1. \-global::train_batch(b)
  2.   +-torchvision:::model(b[[1]])
  3.   | \-self$conv1(x)
  4.   |   \-self$conv_forward_(input, self$weight)
  5.   |     \-torch::nnf_conv2d(...)
  6.   |       \-torch::torch_conv2d(...)
  7.   |         \-base::mget(...)
  8.   +-b[[1]]
  9.   \-torch:::`[[.enum_env`(b, 1)
 10.     \-parent.env(x)$.iter$.next()
 11.       \-self$.next_data()
 12.         \-self$.pop_task()
 13.           \-torch:::runtime_error(result$error$message)
```

Where "transform_normalize" is a part of the image transformation function:
```
train_transforms <- function(img) {
  img %>%
    # first convert image to tensor
    transform_to_tensor() %>%
    # then move to the GPU (if available)
    (function(x) x$to(device = device)) %>%
    # data augmentation
    transform_random_resized_crop(size = c(224, 224)) %>%
    # data augmentation
    transform_color_jitter() %>%
    # data augmentation
    transform_random_horizontal_flip() %>%
    # normalize according to what is expected by resnet
    transform_normalize(mean = c(0.485, 0.456, 0.406), std = c(0.229, 0.224, 0.225))
}
```

**Comment by dfalbel** [comment]
A workaround for the first issue might be to call `gc` in the training loop here. You can find an explanation why it should work [here](https://github.com/mlverse/torch/issues/396#issuecomment-748461255).

This is not yet fixed for GPU's though, and we plan to fix this in the next release.

**Comment by LordRudolf** [comment]
Thanks but again, now I've got another error:

``` r
  

library(torch)
library(torchvision)
library(torchdatasets)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(dplyr)
library(ggplot2)

########################################################################################
## 1 Define functions and data

device <- if (cuda_is_available()) torch_device("cuda:0") else "cpu"

train_transforms <- function(img) {
  img %>%
    # first convert image to tensor
    transform_to_tensor() %>%
    # then move to the GPU (if available)
    (function(x) x$to(device = device)) %>%
    # data augmentation
    transform_random_resized_crop(size = c(224, 224)) %>%
    # data augmentation
    transform_color_jitter() %>%
    # data augmentation
    transform_random_horizontal_flip() %>%
    # normalize according to what is expected by resnet
    transform_normalize(mean = c(0.485, 0.456, 0.406), std = c(0.229, 0.224, 0.225))
}
valid_transforms <- function(img) {
  img %>%
    transform_to_tensor() %>%
    (function(x) x$to(device = device)) %>%
    transform_resize(256) %>%
    transform_center_crop(224) %>%
    transform_normalize(mean = c(0.485, 0.456, 0.406), std = c(0.229, 0.224, 0.225))
}
test_transforms <- valid_transforms

data_dir <- './image_classification/data/100-bird-species'

train_ds <- image_folder_dataset(file.path(data_dir, "train"), transform = train_transforms)
valid_ds <- image_folder_dataset(file.path(data_dir, "valid"), transform = train_transforms)
test_ds <- image_folder_dataset(file.path(data_dir, "test"), transform = train_transforms)
class_names <- test_ds$classes


batch_size <- 128

worker_fun <- function(id) {
  library(torch)
  library(torchvision)
  library(torchdatasets)
  library(torchvision)
  device <- if (cuda_is_available()) torch_device("cuda:0") else "cpu"
}
train_dl <- dataloader(train_ds, batch_size = batch_size, shuffle = TRUE, num_workers = 4, worker_init_fn = worker_fun)
valid_dl <- dataloader(valid_ds, batch_size = batch_size, num_workers = 4, worker_init_fn = worker_fun)
test_dl <- dataloader(test_ds, batch_size = batch_size,  num_workers = 4, worker_init_fn = worker_fun)


model <- model_resnet18(pretrained = TRUE)
model$parameters %>% purrr::walk(function(param) param$requires_grad_(FALSE))

num_features <- model$fc$in_features

model$fc <- nn_linear(in_features = num_features, out_features = length(class_names))

model <- model$to(device = torch_device("cuda:0"))

criterion <- nn_cross_entropy_loss()

optimizer <- optim_sgd(model$parameters, lr = 0.05, momentum = 0.9)

num_epochs = 10
batch_size <- 128

scheduler <- optimizer %>% 
  lr_one_cycle(max_lr = 0.05, epochs = num_epochs, steps_per_epoch = train_dl$.length())

########################################################################################
## 5 Training loop

train_batch <- function(b) {
  
  optimizer$zero_grad()
  output <- model(b[[1]])
  loss <- criterion(output, b[[2]]$to(device = torch_device("cuda:0")))
  loss$backward()
  optimizer$step()
  scheduler$step()
  loss$item()
  
}

valid_batch <- function(b) {
  
  output <- model(b[[1]])
  loss <- criterion(output, b[[2]]$to(device = torch_device("cuda:0")))
  loss$item()
}


for (epoch in 1:num_epochs) {
  
  model$train()
  train_losses <- c()
  
  for (b in enumerate(train_dl)) {
    loss <- train_batch(b)
    train_losses <- c(train_losses, loss)
  }
  
  model$eval()
  valid_losses <- c()
  
  for (b in enumerate(valid_dl)) {
    loss <- valid_batch(b)
    valid_losses <- c(valid_losses, loss)
  }
  
  cat(sprintf("\nLoss at epoch %d: training: %3f, validation: %3f\n", epoch, mean(train_losses), mean(valid_losses)))
}
#> Error: callr subprocess failed: object 'device' not found
```

<sup>Created on 2021-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dfalbel** [comment]
You might want to have `device <<- if (cuda_is_available()) torch_device("cuda:0") else "cpu"` in the worker_init_fn. Notice the `<<-` instead of `<-`. Sorry it's hard to use yet. We will make this easier with #444

**Comment by LordRudolf** [comment]
Thank you. It worked.
