### ISSUE TITLE
Indexing of R Torch "._version" attribute

### ISSUE THREAD

**Issue by dominikj2** [mlverse/torch#642]
Hi ,

I am getting a below error after the second pass of `coro::loop(for (b in ld_train) {}`. It happens during the forward pass (second time round after backward() worked).  The following link has problems with second pass due to `._version` attribute in Pytorch being changed but R does not have an equivalent `._version` attribute: [https://discuss.pytorch.org/t/trouble-understanding-version-semantics/115442](url)

I wonder if my error is associated with `_version` indexing.  

Either way, the error message is not helpful when  it provides `[<unknown file> @ <unknown line number>]`. Note that below error runs `iou_loss$backward()` and NOT `with_detect_anomaly({ iou_loss$backward() })` which also had `unknown line number` as discussed in #634 

```
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [4,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [5,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [6,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [7,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [16,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: block: [3,0,0], thread: [17,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Error in (function (self, dim, index, sparse_grad)  : 
  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from _launch_scatter_gather_kernel at C:/w/b/windows/pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:79 (most recent call first):
00007FFB909610D200007FFB90961070 c10.dll!c10::Error::Error [<unknown file> @ <unknown line number>]
00007FFBC3BEE30600007FFBC3BEE290 c10_cuda.dll!c10::CUDAError::CUDAError [<unknown file> @ <unknown line number>]
00007FFB2A3DB47900007FFB2A3CF310 torch_cuda_cu.dll!at::native::cummin_helper_cuda [<unknown file> @ <unknown line number>]
00007FFB2A3DFDE500007FFB2A3CF310 torch_cuda_cu.dll!at::native::cummin_helper_cuda [<unknown file> @ <unknown line number>]
00007FFB2A3DCA7C00007FFB2A3CF310 torch_cuda_cu.dll!at::native::cummin_helper_cuda [<unknown file> @ <unknown line number>]
00007FFB2A3E220D00007FFB2A3CF310 torc
```

This similar pytorch issue is solved with line number details: [https://github.com/pytorch/pytorch/issues/21136](url)

The above error message is sometimes replaced with below error message without any obvious changes to code. Debugging the below error message lead to a bug in `contrib_sort_vertices`. The output of this function represent index values of vertices that need to be sorted. Issue #608 was resolved with `contrib_sort_vertices`, which used a python code that is 0-base (R should be 1-base). This is a bug that I temporarily fixed in my code with `sorted_indices = sorted_indices + 1L`

```
Error in (function (self, dim, index, sparse_grad)  : 
  Indexing starts at 1 but found a 0.
```

Still confused with first error message but it has been narrowed down to the below two line of code:
```

 idx_ext = idx_sorted$unsqueeze(-1)$'repeat'(c(1,1,1,2))
 selected = torch_gather(vertices, 2, idx_ext)
```
which translate the below python code:
```
    idx_ext = idx_sorted.unsqueeze(-1).repeat([1,1,1,2])
    selected = torch.gather(vertices, 2, idx_ext)
```

To reproduce, I have pushed all the changes to [https://github.com/dominikj2/Torch_R_GIoU_3dRotated_BBox_Loss](). In **_TORCH_GIoU_Rotating_3d_LOSS_MAIN.R_** file, the DATA_DIR is the directory for  generating data (NOTE: code does not require any data as it generates test data), and the SOURCE_DIR is where the repository is stored on the local computer.

Any support with above error would be great. I will keep on trying to debug in the meantime.

**Comment by dominikj2** [comment]
This Error has been resolved by recognizing that the` dim` argument in pythons` torch.gather` is 0-base, so Python's:
`selected = torch.gather(vertices, 2, idx_ext)`
should be
`selected = torch_gather(vertices, 3, idx_ext)`
when trainslating into R

The above error message may be confusing as it is for python 0-base, as shown in relevant snippet below (>=0): 

`Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed`

**Note: the new `contrib_sort_vertices` function still needs a bug fix as it outputs indices that are 0-base .**

Using temporary fix: `sorted_indices = sorted_indices + 1L`
