### ISSUE TITLE
Failure to load JIT traced module in R (from Python) with CUDA 'no kernel image is available' error

### ISSUE THREAD

**Issue by rdinnager** [mlverse/torch#722]
I am using `jit_load()` to try and load into R a GPU model that I created with `torch.jit.trace()` in Python and get the following error:

```
Error in cpp_jit_load(path) : 
  CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from launch_vectorized_kernel at /pytorch/aten/src/ATen/native/cuda/CUDALoops.cuh:104 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x69 (0x2ba70b6391d9 in /usr/local/lib/R/site-library/torch/deps/./libc10.so)
frame #1: <unknown function> + 0x12faff0 (0x2ba727cd1ff0 in /usr/local/lib/R/site-library/torch/deps/./libtorch_cuda.so)
frame #2: void at::native::gpu_kernel_impl<at::native::CompareEqFunctor<float> >(at::TensorIteratorBase&, at::native::CompareEqFunctor<float> const&) + 0xd72 (0x2ba72840a522 in /usr/local/lib/R/site-library/torch/deps/./libtorch_cuda.so)
frame #3: void at::native::gpu_kernel<at::nativ
```

I have confirmed that CUDA is available:
```
library(torch)
cuda_is_available()
> [1] TRUE
```

And that is works:
```
torch_tensor(c(1, 1))$cuda()
> torch_tensor
>  1
>  1
> [ CUDAFloatType{2} ]
```

Any idea what could be wrong?

**Comment by dfalbel** [comment]
Could it be possible that the traced module was created with a much more recent CUDA or PyTorch version than the one torch is using?
Does setting `CUDA_LAUNCH_BLOCKING=1` env var and running that code change the error message? In general this CUDA errors happen in asynchronous code and maybe the error is actually something else. I think you need to set the env var before loading torch.

**Comment by rdinnager** [comment]
Thanks for the quick reply. I am not sure about CUDA versions. I am using the same machine as I trained the model in Python on, but I didn't install `torch` myself, the HPC staff did and it is a little bit complicated because R is run from a singularity container so I will need to talk to them. In any case, I tried loading the `.pt` file on another machine and it worked! Well, the loading worked. When I actually try and use the model I get a somewhat more informative error, though I'm not entirely sure where to start with debugging.. I doubt this will be much help, but I will post it here in case anything pops to mind based on your experience:

```
Error in cpp_call_jit_script(ptr, inputs) : 
  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_utils/persistence.py", line 11, in forward
    tensor: Tensor,
    argument_2: Tensor) -> Tensor:
    _0 = (self.synthesis).forward((self.mapping).forward(tensor, ), )
          ~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _0
class SynthesisNetwork(Module):
  File "code/__torch__/torch_utils/persistence.py", line 59, in forward
    _20 = (_9).forward((_10).forward(_19, tensor4, ), tensor5, )
    _21 = (_7).forward((_8).forward(_20, tensor6, ), tensor7, )
    _22 = (_5).forward((_6).forward(_21, tensor8, ), tensor9, )
           ~~~~~~~~~~~ <--- HERE
    _23 = (_3).forward((_4).forward(_22, tensor10, ), tensor11, )
    _24 = (_1).forward((_2).forward(_23, tensor12, ), tensor13, )
  File "code/__torch__/torch_utils/persistence/___torch_mangle_20.py", line 76, in forward
    _33 = [_28, _31, _32, 1, int(in_width), 1]
    i
```

Anyway, feel free to close this issue as the original issue has been (sort of) resolved by using another machine.

**Comment by rdinnager** [comment]
Is it me or is the error cut off? Is there a way to may sure I am getting the whole traceback from TorchScript? I tried running the model in a piece-wise fashion and narrowed down the problem a bit more, but it also looks like the message is getting cut off around the 20th line (similar to above):

```
Error in cpp_call_jit_script(ptr, inputs) : 
  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_utils/persistence.py", line 59, in forward
    _20 = (_9).forward((_10).forward(_19, tensor4, ), tensor5, )
    _21 = (_7).forward((_8).forward(_20, tensor6, ), tensor7, )
    _22 = (_5).forward((_6).forward(_21, tensor8, ), tensor9, )
           ~~~~~~~~~~~ <--- HERE
    _23 = (_3).forward((_4).forward(_22, tensor10, ), tensor11, )
    _24 = (_1).forward((_2).forward(_23, tensor12, ), tensor13, )
  File "code/__torch__/torch_utils/persistence/___torch_mangle_20.py", line 76, in forward
    _33 = [_28, _31, _32, 1, int(in_width), 1]
    input0 = torch.reshape(x2, _33)
    x3 = torch.constant_pad_nd(input0, [0, 3, 0, 0, 0, 3])
         ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _34 = int(torch.mul(in_height, CONSTANTS.c13))
    _35 = int(torch.mul(in_width, CONSTANTS.c13))

Traceback of TorchScript, original code (most recent c
```

**Comment by dfalbel** [comment]
It seems that R itself truncates error messages:

> Errors will be truncated to getOption("warning.length") characters, default 1000.

Maybe setting a larger value will allow you to see the actual problem.
If you are using PyTorch extensions when training that model, It could be a missing TorchScript operator.
Otherwise it could be a forward compatibility problem where the model is trained with a more recent version of PyTorch that implements an operator that older versions don't have a available.

**Comment by rdinnager** [comment]
You are right, I should have realised that! When I increase the `warning.length` option I see the whole message:

```
Error in cpp_call_jit_script(ptr, inputs) : 
  The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/torch_utils/persistence.py", line 59, in forward
    _20 = (_9).forward((_10).forward(_19, tensor4, ), tensor5, )
    _21 = (_7).forward((_8).forward(_20, tensor6, ), tensor7, )
    _22 = (_5).forward((_6).forward(_21, tensor8, ), tensor9, )
           ~~~~~~~~~~~ <--- HERE
    _23 = (_3).forward((_4).forward(_22, tensor10, ), tensor11, )
    _24 = (_1).forward((_2).forward(_23, tensor12, ), tensor13, )
  File "code/__torch__/torch_utils/persistence/___torch_mangle_20.py", line 76, in forward
    _33 = [_28, _31, _32, 1, int(in_width), 1]
    input0 = torch.reshape(x2, _33)
    x3 = torch.constant_pad_nd(input0, [0, 3, 0, 0, 0, 3])
         ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _34 = int(torch.mul(in_height, CONSTANTS.c13))
    _35 = int(torch.mul(in_width, CONSTANTS.c13))

Traceback of TorchScript, original code (most recent call last):
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/nn/functional.py(4153): _pad
/blue/anna.simonse/r.dinnage/Projects/stylegan3/torch_utils/ops/upfirdn2d.py(188): _upfirdn2d_ref
/blue/anna.simonse/r.dinnage/Projects/stylegan3/torch_utils/misc.py(103): decorator
/blue/anna.simonse/r.dinnage/Projects/stylegan3/torch_utils/ops/upfirdn2d.py(162): upfirdn2d
/blue/anna.simonse/r.dinnage/Projects/stylegan3/torch_utils/ops/filtered_lrelu.py(146): _filtered_lrelu_ref
/blue/anna.simonse/r.dinnage/Projects/stylegan3/torch_utils/misc.py(103): decorator
/blue/anna.simonse/r.dinnage/Projects/stylegan3/torch_utils/ops/filtered_lrelu.py(116): filtered_lrelu
/blue/anna.simonse/r.dinnage/Projects/stylegan3/training/networks_stylegan3.py(364): forward
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py(1051): _call_impl
/blue/anna.simonse/r.dinnage/Projects/stylegan3/training/networks_stylegan3.py(482): forward
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py(1051): _call_impl
/blue/anna.simonse/r.dinnage/Projects/stylegan3/training/networks_stylegan3.py(523): forward
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py(1039): _slow_forward
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/nn/modules/module.py(1051): _call_impl
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/jit/_trace.py(952): trace_module
/home/r.dinnage/.conda/envs/stylegan3/lib/python3.9/site-packages/torch/jit/_trace.py(735): trace
<stdin>(1): <module>
RuntimeError: CUDA out of memory. Tried to allocate 706.00 MiB (GPU 0; 8.00 GiB total capacity; 6.15 GiB already allocated; 0 bytes free; 6.65 GiB reserved in total by PyTorch)
```

Turns out it is just an ordinary memory exhausted error 😅 . I did train the model on an A100, and on this other machine I have much less memory on my GPU. Good to know!

I'm closing this issue. Thanks for your help, and thanks for the ever more awesome package!
